name: Publish Quarto Document

on:
  push:
  branches: [main]

jobs:
  build-deploy:
  runs-on: ubuntu-latest

steps:
  - name: Checkout repository
uses: actions/checkout@v3

- name: Setup Quarto
uses: quarto-dev/quarto-actions/setup@v2

- name: Setup R
uses: r-lib/actions/setup-r@v2

- name: Install R packages
run: |
  Rscript -e 'install.packages(c("readr", "readxl", "writexl", "dplyr", "ggplot2", "lubridate", "scales", "stringr", "tidyr", "RColorBrewer", "pheatmap", "plotly", "reshape2"))'

- name: Render Quarto HTML
run: quarto render

- name: Publish to GitHub Pages
uses: quarto-dev/quarto-actions/publish@v2
with:
  target: gh-pages
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}